import torch
from .eval import *
from .attacks import *
from .datasets import *

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

TGDA_CONFIG = {
    'cifar10': {
        'poisoner_model': CIFAR10Poisoner,
        'poisoner_load_file': '.tar',
        'poisoner_model_steps': 1,
        'poisoner_model_step_size': 0.1,
        'poisoned_model': CIFAR10PoisonedResnetWithPretraining,
        'poisoned_model_steps': 10,
        'poisoned_model_optimizer': lambda params: torch.optim.SGD(params, lr=0.001, momentum=0.9),
        'train_loss': poisoned_ce_loss,
        'test_loss': ce_loss,
        'eval_metric': accuracy,
        'train_loader': get_cifar10_train_loader('./data', batch_size=1000),
        'test_loader': get_cifar10_test_loader('./data', batch_size=1000),
        'train_ratio':0.7,
        'epsilon': 0.03,
        'epochs': 2000,
        'print_epochs': 1,
        'save_folder': './checkpoints/tgda/cifar10/',
        'device': device,
    },
    'mnist': {
        'poisoner_model': MNISTPoisoner,
        'poisoner_load_file': None,
        'poisoner_model_steps': 1,
        'poisoner_model_step_size': 0.1,
        'poisoned_model': MNISTPoisonedLR,
        'poisoned_model_steps': 10,
        'poisoned_model_optimizer': lambda params: torch.optim.SGD(params, lr=0.1, momentum=0.9),
        'train_loss': poisoned_ce_loss,
        'test_loss': ce_loss,
        'eval_metric': accuracy,
        'train_loader': get_mnist_train_loader('./data', batch_size=50000),
        'test_loader': get_mnist_test_loader('./data', batch_size=1000),
        'train_ratio':0.7,
        'epsilon': 0.03,
        'epochs': 200,
        'print_epochs': 1,
        'save_folder': './checkpoints/tgda/mnist/',
        'device': device,
    },
}

GC_CONFIG = {
    'cifar10': {
        'model': CIFAR10PoisonedResnetWithMOCOPretraining,
        'sum_loss_fn': lambda model, X, y: ce_loss(model, X, y, reduction='sum'),
        'mean_loss_fn': ce_loss,
        'optimizer': lambda params: torch.optim.SGD(params, lr=0.1, momentum=0.9),
        'pc_optimizer': lambda params: ParamCorrupter(params, lr=0.1, eps=1, LP='l2'),
        'data_optimizer': lambda params: torch.optim.SGD(params, lr=10, momentum=0.9),
        'eval_metric': accuracy,
        'train_loader': get_cifar10_train_loader('./data', batch_size=1000),
        'test_loader': get_cifar10_test_loader('./data', batch_size=1000),
        'epsilon': 0.03,
        'epochs': 10,
        'gc_epochs': 100,
        'print_epochs': 2,
        'save_folder': './checkpoints/gc/cifar10/',
        'device': device,
        'initialization': 'real',
    },
    'mnist': {
        'model': MNISTPoisonedLR,
        'sum_loss_fn': lambda model, X, y: ce_loss(model, X, y, reduction='sum'),
        'mean_loss_fn': ce_loss,
        'optimizer': lambda params: torch.optim.SGD(params, lr=0.00001, momentum=0),
        'pc_optimizer': lambda params: ParamCorrupter(params, lr=0.1, eps=1, LP='l2'),
        'data_optimizer': lambda params: torch.optim.SGD(params, lr=1, momentum=0.9),
        'eval_metric': accuracy,
        'train_loader': get_mnist_train_loader('./data', batch_size=1),
        'test_loader': get_mnist_test_loader('./data', batch_size=1000),
        'epsilon': 0.03,
        'epochs': 4,
        'gc_epochs': 10000,
        'print_epochs': 1,
        'save_folder': './checkpoints/gc/mnist/',
        'device': device,
        'initialization': 'real',
    }
}

DM_CONFIG = {
    'cifar10': {
        'model': CIFAR10PoisonedResnetWithMOCOPretraining,
        'loss_fn': ce_loss,
        'optimizer': lambda params: torch.optim.SGD(params, lr=0.1, momentum=0.9),
        'data_optimizer': lambda params: torch.optim.SGD(params, lr=0.1, momentum=0.9),
        'eval_metric': accuracy,
        'train_loader': get_cifar10_train_loader('./data', batch_size=1000),
        'test_loader': get_cifar10_test_loader('./data', batch_size=1000),
        'epsilon': 0.03,
        'epochs': 1000,
        'print_epochs': 2,
        'save_folder': './checkpoints/dm/cifar10/',
        'device': device,
        'initialization': 'random',
    },
    'mnist': {
        'model': PretrainedMNISTPoisonedLR,
        'loss_fn': ce_loss,
        'optimizer': lambda params: torch.optim.SGD(params, lr=1, momentum=0.9),
        'data_optimizer': lambda params: torch.optim.SGD(params, lr=0.1, momentum=0.9),
        'eval_metric': accuracy,
        'train_loader': get_mnist_train_loader('./data', batch_size=1000),
        'test_loader': get_mnist_test_loader('./data', batch_size=1000),
        'epsilon': 0.03,
        'epochs': 100,
        'print_epochs': 2,
        'save_folder': './checkpoints/dm/mnist/',
        'device': device,
        'initialization': 'random',
    },
}


LD_CONFIG = {
    'cifar10': {
        'model': CIFAR10PoisonedResnet,
        'loss_fn': ce_loss,
        'optimizer': lambda params: torch.optim.SGD(params, lr=0.1, momentum=0.9),
        'eval_metric': accuracy,
        'train_loader': get_cifar10_train_loader('./data', batch_size=1000),
        'test_loader': get_cifar10_test_loader('./data', batch_size=1000),
        'magnitude': 1000,
        'poisoned_batch_size': 1500,
        'epochs': 50,
        'print_epochs': 1,
        'save_folder': './checkpoints/ld/cifar10/',
        'device': device,
    },
    'mnist': {
        'model': MNISTPoisonedLR,
        'loss_fn': ce_loss,
        'optimizer': lambda params: torch.optim.SGD(params, lr=0.01, momentum=0.9),
        'eval_metric': accuracy,
        'train_loader': get_mnist_train_loader('./data', batch_size=1000),
        'test_loader': get_mnist_test_loader('./data', batch_size=1000),
        'magnitude': 10000000,
        'poisoned_batch_size': 1,
        'epochs': 20,
        'print_epochs': 1,
        'save_folder': './checkpoints/ld/mnist/',
        'device': device,
    },
}